# Generated by Django 3.1.5 on 2021-01-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
